---
- hosts: all
  become: true
  vars:
    ubuntu_packages:
      - python
      - python-pip
      - git
      - docker.io
    pip_packages:
      - ansible
      - molecule == 2.22
      - docker
    enable_services:
      - docker

  pre_tasks:
    - name: prepare host
      include_role:
        name: preflight

  tasks:
    - name: config | Download code from forked repo.
      git:
        repo: "https://github.com/YukonSpector/ansible-frr"
        dest: "~/ansible-frr"
      become: false