---
# preflight role default tasks main.yaml file

# Update apt-cache to ensure up to date
- name: update | Apt Cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

# Install pre-reqs for Ansible install
- name: install | OS Ansible Pre-Reqs.
  apt:
    name: "{{ ubuntu_packages }}"
    state: present
  become: true

# enable and start services.
- name: config | Services.
  service:
    enabled: "yes"
    name: "{{ item }}"
    state: "started"
  with_items: "{{ enable_services }}"

# Add vagrant to docker group so doceker can be used without sudo.
- name: config | Add to docker group.
  user:
    name: "vagrant"
    groups: docker
    append: yes

# Install packages for python via pip.
- name: install | Pip packages.
  pip:
    name: "{{ pip_packages }}"
    state: present
    executable: "pip"
  become: true